from app.models import db, Affirmation
from datetime import datetime

affirmation_bodies = ["Asking for help is a sign of self-respect and self-awareness.",
"Changing my mind is a strength, not a weakness.",
"Every decision I make is supported by my whole and inarguable experience.",
"I affirm and encourage others, as I do myself.",
"I alone hold the truth of who I am.",
"I am allowed to ask for what I want and what I need.",
"I am allowed to feel good.",
"I am capable of balancing ease and effort in my life.",
"I am complete as I am, others simply support me.",
"I am content and free from pain.",
"I am doing the work that works for me.",
"I am good and getting better.",
"I am growing and I am going at my own pace.",
"I am held and supported by those who love me.",
"I am in charge of how I feel and I choose to feel happy.",
"I am listening and open to the messages the universe has to offer today.",
"I am loved and worthy.",
"I am more than my circumstances dictate.",
"I am open to healing.",
"I am optimistic because today is a new day.",
"I am peaceful and whole.",
"I am proof enough of who I am and what I deserve.",
"I am responsible for myself, and I start there.",
"I am safe and surrounded by love and support.",
"I am still learning so it’s okay to make mistakes.",
"I am understood and my perspective is important.",
"I am valued and helpful.",
"I am well-rested and excited for the day.",
"I am worthy of investing in myself.",
"I belong here, and I deserve to take up space.",
"I breath in healing, I exhale the painful things that burden my heart.",
"I breathe in trust, I exhale doubt.",
"I can be soft in my heart and firm in my boundaries.",
"I can control how I respond to things that are confronting.",
"I can hold two opposing feelings at once, it means I am processing.",
"I celebrate the good qualities in others and myself.",
"I deserve an affirming touch on my own terms.",
"I deserve information and I deserve moments of silence, too.",
"I deserve self-respect and a clean space.",
"I do all things in love.",
"I do not have to linger in dark places; there is help for me here.",
"I do not pretend to be anyone or anything other than who I am.",
"I do not rise and fall for another.",
"I do not rush through my life, I temper speed with stillness.",
"I embrace change seamlessly and rise to the new opportunity it presents.",
"I embrace the questions in my heart and welcome the answers in their own time.",
"I grow towards my interests, like a plant reaching for the sun.",
"I have come farther than I would have ever thought possible, and I'm learning along the way.",
"I have everything I need to succeed.",
"I hold community for others, and am held in community by others.",
"I hold wisdom beyond knowledge.",
"I invite abundance and a generous heart.",
"I invite art and music into my life.",
"I leave room in my life for spontaneity.",
"I let go of the things that sit achingly out of reach.",
"I look forward to tomorrow and the opportunities that await me.",
"I love that I love what I love.",
"I make decisions based on a good gut, I make changes based on a growing heart.",
"I make time to experience grief and sadness when necessary.",
"I nourish myself with kind words and joyful foods.",
"I practice gratitude for all that I have, and all that is yet to come.",
"I release the fears that do not serve me.",
"I respect the cycle of the seasons.",
"I seek out mystery in the ordinary.",
"I strive for joy, not for perfection.",
"I tell the truth about who I am and what I need from others.",
"I uplift my joy and the joy of others.",
"I welcome the wisdom that comes with growing older.",
"I welcome what is, I welcome what comes.",
"I will allow myself to evolve.",
"Letting go creates space for opportunities to come.",
"My body is beautiful in this moment and at its current size.",
"My body is worthy of being cared for and adorned in beautiful garments.",
"My feelings deserve names, deserve recognition, deserve to be felt.",
"My heart is open to helpfulness from myself and from others.",
"My heart knows its own way.",
"My life is not a race or competition.",
"My perspective is unique and important.",
"My pleasure does not require someone else's pain.",
"My sensitivity is beautiful, and my feelings and emotions are valid.",
"My weirdness is wonderful.",
"Saying “no” is an act of self-affirmation, too.",
"Sometimes the work is resting.",
"There is growth in stillness.",
"There is peace in changing your mind when it is done in love.",
"There is poetry in everything, if I look for it.",
"There is room for me at the table.",
"There is something in this world that only I can do. That is why I am here.",
"There is strength in quiet, there is vulnerability in being loud.",
"Today I celebrate that I am younger than I’m ever going to be.",
"Today is an opportunity to grow and learn.",
"When I feel fear, I feed trust.",
"When I focus on my reason for being, I am infinitely brave.",
"When I forgive myself, I free myself.",
"When I release shame, I move into myself more beautifully.",
"When I root into the earth, the earth rises to support me.",
"When I speak my needs, I receive them abundantly.",
"When I talk to myself as I would a friend, I see all my best qualities and I allow myself to shine.",
"Words may shape me, but they do not make me.",
"Asking for help is a sign of self-respect and self-awareness.",
"Changing my mind is a strength, not a weakness.",
"Every decision I make is supported by my whole and inarguable experience.",
"I affirm and encourage others, as I do myself.",
"I alone hold the truth of who I am.",
"I am allowed to ask for what I want and what I need.",
"I am allowed to feel good.",
"I am capable of balancing ease and effort in my life.",
"I am complete as I am, others simply support me.",
"I am content and free from pain.",
"I am doing the work that works for me.",
"I am good and getting better.",
"I am growing and I am going at my own pace.",
"I am held and supported by those who love me.",
"I am in charge of how I feel and I choose to feel happy.",
"I am listening and open to the messages the universe has to offer today.",
"I am loved and worthy.",
"I am more than my circumstances dictate.",
"I am open to healing.",
"I am optimistic because today is a new day.",
"I am peaceful and whole.",
"I am proof enough of who I am and what I deserve.",
"I am responsible for myself, and I start there.",
"I am safe and surrounded by love and support.",
"I am still learning so it’s okay to make mistakes.",
"I am understood and my perspective is important.",
"I am valued and helpful.",
"I am well-rested and excited for the day.",
"I am worthy of investing in myself.",
"I belong here, and I deserve to take up space.",
"I breath in healing, I exhale the painful things that burden my heart.",
"I breathe in trust, I exhale doubt.",
"I can be soft in my heart and firm in my boundaries.",
"I can control how I respond to things that are confronting.",
"I can hold two opposing feelings at once, it means I am processing.",
"I celebrate the good qualities in others and myself.",
"I deserve an affirming touch on my own terms.",
"I deserve information and I deserve moments of silence, too.",
"I deserve self-respect and a clean space.",
"I do all things in love.",
"I do not have to linger in dark places; there is help for me here.",
"I do not pretend to be anyone or anything other than who I am.",
"I do not rise and fall for another.",
"I do not rush through my life, I temper speed with stillness.",
"I embrace change seamlessly and rise to the new opportunity it presents.",
"I embrace the questions in my heart and welcome the answers in their own time.",
"I grow towards my interests, like a plant reaching for the sun.",
"I have come farther than I would have ever thought possible, and I'm learning along the way.",
"I have everything I need to succeed.",
"I hold community for others, and am held in community by others.",
]

def seed_affirmations():
    Affirmation1 = Affirmation(
        body="I am in the right place at the right time, doing the right thing", image_url='', viewed= False, user_id=1, created_at=datetime.now(), updated_at=datetime.now())
    Affirmation2 = Affirmation(
        body="Make way for the unprecedented and watch your reality rearrange yourself", image_url='https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/yrsa-daley-ward-1621436133.jpg?crop=1xw:1xh;center,top&resize=980:*', viewed= False, user_id=1, created_at=datetime.now(), updated_at=datetime.now())
    Affirmation3 = Affirmation(
        body="The chance to love and be loved exists no matter where you are", image_url='', viewed= True, user_id=2, created_at=datetime.now(), updated_at=datetime.now())


    db.session.add(Affirmation1)
    db.session.add(Affirmation2)
    db.session.add(Affirmation3)

    db.session.commit()


# Uses a raw SQL query to TRUNCATE the users table.
# SQLAlchemy doesn't have a built in function to do this
# TRUNCATE Removes all the data from the table, and RESET IDENTITY
# resets the auto incrementing primary key, CASCADE deletes any
# dependent entities
def undo_affirmations():
    db.session.execute('TRUNCATE affirmations RESTART IDENTITY CASCADE;')
    db.session.commit()
