"""empty message

Revision ID: 34617a1be204
Revises: e16cecb62eff
Create Date: 2022-02-15 11:33:47.405777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34617a1be204'
down_revision = 'e16cecb62eff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affirmations', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'affirmations', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'affirmations', type_='foreignkey')
    op.drop_column('affirmations', 'user_id')
    # ### end Alembic commands ###
